using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModelsLibrary
{
    public class PurchaseOrderHeaderModel
    {
        /// <summary>
        /// Holds the unique purchase order number generated by database
        /// </summary>
        public int PurchaseOrderID { get; set; }

        /// <summary>
        /// Holds the vendor ID (Key)
        /// </summary>
        public int VendorID { get; set; }

        /// <summary>
        /// The vendors sales id
        /// </summary>
        public string? VendorReference { get; set; }

        /// <summary>
        /// The date the order is created
        /// </summary>
        public DateTime OrderDate { get; set; }

        /// <summary>
        /// The total value of the products purchased
        /// </summary>
        public decimal OrderAmount { get; set; }

        /// <summary>
        /// VAT percentage
        /// </summary>
        public double VATPercentage { get; set; }

        /// <summary>
        /// The VAT on the order amount
        /// </summary>
        public decimal VATAmount { get; set; }

        /// <summary>
        /// The sum of the OrderAmount and VATAmount
        /// </summary>
        public decimal TotalAmount { get; set; }

        /// <summary>
        /// The date the products purchased are expected
        /// </summary>
        public DateOnly RequiredDate { get; set; }

        /// <summary>
        /// Indicates if the order is complete or not
        /// </summary>
        public bool OrderFilled { get; set; }
    }
}
